#!/bin/bash
#
# A simple script to push both CImg and G'MIC updates on the git repo.
#
COM="."
if [ -n "$*" ]; then COM="$*"; fi
cd $HOME/work/src/CImg
git commit -uno -am "$COM"
git push
cd $HOME/work/src/gmic
git commit -uno -am "$COM"
git push
cd $HOME/work/src/gmic-community
git pull
git commit -uno -am "$COM"
git push

cd $HOME/work/src/gmic
cp -rf COPYING README src/*.cpp src/*.h src/Makefile src/*.scm zart $HOME/work/src/gmic-minimal
cp -rf COPYING README src/*.cpp src/*.h src/Makefile src/*.scm zart $HOME/work/src/gmic-minimal-mirror
rsync -az * $HOME/work/src/gmic-mirror

cd $HOME/work/src/gmic-minimal
git commit -uno -am "$COM"
git push
cd $HOME/work/src/gmic-minimal-mirror
git commit -uno -am "$COM"
git push
cd $HOME/work/src/gmic-mirror
git commit -uno -am "$COM"
git push
